[package]
name = "pong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.12.0"
env_logger = "0.9.0"
winit = "0.26.0"
pollster = "0.2.4"
cgmath = "0.18"
log = "0.4"
image = "0.23"